---
title: "Module Information"
format: html
editor: visual
---

## Course organisation

**Lecture and Lab Timetable**

-   Monday 11am (Lecture, CB8), Wednesday 2pm (Lecture, CH)

-   Tuesday 3pm (Lab, TSI239), Friday 9am (Lab, TSI239)

    -   Labs will start in week 2

    -   Please confirm your choice on Moodle.

**Tutorials**

-   Tuesdays \@ 9am, 10am, 2pm, 3pm, 5pm,  Wednesdays \@ 12pm, 1pm
-   Tutorials -- starting week 4 (24/02/2025)

**Office hours**

-   By appointment

## Materials and Assessments


**Notes**

-   Notes will be a combination of links posted on Moodle and notes taken down in class

**Tutorial Questions**

- Practice tutorial questions will be posted to Moodle. 

**Assignments**

-  Assignment questions will be posted to Moodle and answers should be uploaded as PDFs. 

**Lab Quizzes**

-   Each lab will have an associated quiz that will be a Moodle Quiz format with multiple attempts allowed until the end of the semester. 

**Midterm Exam**

- The midterm exam will be a Moodle Quiz MCQ.


**Marks**

-   10% -- compulsory assignments

-   10% -- quizzes

-   15% -- mid-term exam (March 28th, MCQ)

-   65% -- final exam (date TBC)



**Recommended reading**

-   R for Data Science (https://r4ds.had.co.nz)

## Topics Covered

-   [ ] **Tidyverse Recap** 

-   [ ] **Correlation (and Causation)** 

-   [ ] **Observational Studies** 

-   [ ] **Controlled Experiments** 

-   [ ] **Surveys** 

-   [ ] **Data Privacy and Anonymisation** 

-   [ ] **Supervised and Unsupervised Learning** 

-   [ ] **Predictive Analytics** 

-   [ ] **Image and Text Analysis** 






## Diversity & inclusion

It is my intent to present materials and activities that are respectful of diversity: gender identity, sexuality, disability, age, socioeconomic status, ethnicity, race, nationality, religion, and culture. I may not always get this right so please let me know ways to improve the effectiveness of the course for you personally, or for other students or student groups.

To help with this:

-   If you have a name that differs from those that appear in your official University records, please let me know!

-   Please let me know your preferred pronouns if you wish to do so.

-   I (like many people) am still in the process of learning about diverse perspectives and identities. If something was said in class (by anyone) that made you feel uncomfortable, please talk to me about it.
