---
title: "Welcome to Introduction to Data Science (2)!"
format:
  html:
    link-external-icon: true
    link-external-newwindow: true
---

Welcome to the course website for DS152 Introduction to Data Science (2).

[Module information](https://ncahill89.github.io/DS152/0-Information.html)

Lecture material (slides, notes, videos) are licensed under CC-BY-NC 4.0.

Contact: Niamh Cahill (niamh.cahill\@mu.ie)

## Lecture Notes

1: [Tidyverse Recap](https://ncahill89.github.io/DS152/1-TidyverseRecap.html)

2: [Correlation (and Causation)](https://ncahill89.github.io/DS152/2-Correlation.html)

3: [Multiple Regression Models](https://ncahill89.github.io/DS152/3-MultipleRegression.html)

4: [Sampling Principles and Strategies](https://ncahill89.github.io/DS152/4-sampling.html)

5: [Observational Studies](https://ncahill89.github.io/DS152/5-ObservationalStudies.html)

6: [Experimental Studies](https://ncahill89.github.io/DS152/6-experiments.html)

7: [Predictive Analytics](https://ncahill89.github.io/DS152/7-PredictiveAnalytics.html)

8: [(un)Supervised Learning](https://ncahill89.github.io/DS152/8-(un)supervisedLearning.html)

9: [Text Analysis](https://ncahill89.github.io/DS152/9b-text.html)

10: [Image Analysis](https://ncahill89.github.io/DS152/9-image.html)

## Tutorial Sheets

Tutorial Sheet 1: [Tidyverse Recap](https://ncahill89.github.io/DS152/Tutorial1.html)

Tutorial Sheet 2: [Logistic Regression](https://ncahill89.github.io/DS152/Tutorial2.html)

Tutorial Sheet 3: [Observational Studies](https://ncahill89.github.io/DS152/Tutorial3.html)

Tutorial Sheet 4: [Experimental Studies](https://ncahill89.github.io/DS152/Tutorial4.html)

Tutorial Sheet 5: [Predictive Analytics](https://ncahill89.github.io/DS152/Tutorial6.html)

Tutorial Sheet 6: [(un)Supervised Learning](https://ncahill89.github.io/DS152/Tutorial7.html)


## Assignments

Assignment 1: [Tidyverse Recap](https://ncahill89.github.io/DS152/Assignment1.html)

Assignment 2: [Linear Regression](https://ncahill89.github.io/DS152/Assignment2.html)

Assignment 3: [Sampling and Observational Studies](https://ncahill89.github.io/DS152/Assignment3.html)

Assignment 4: [Experimental Studies](https://ncahill89.github.io/DS152/Assignment4.html)

Assignment 5: [Predictive Analytics](https://ncahill89.github.io/DS152/Assignment5.html)


